# -*- coding: utf-8 -*-
"""Quick replies: the tappable suggestions offered under the assistant's message.

Contract: `docs/v0.0/api/interface-v1.md` §5.5. At most three, labels at most 24
characters, an empty array meaning "render nothing", and stable ids so a suggestion
can be logged and tested.

**Derived from the deterministic layer, never generated by a model.** Two reasons.
The obvious one is that a suggestion the model invents is business logic escaping
into free text. The more practical one is that this runs offline: because the chips
come from rules, they keep working with no model configured, which would not be true
if they were part of the reply generation.

Labels are customer-facing, so they must be safe to show unprompted: no premium
figures, no personalised advice, nothing that implies a recommendation. They are
phrased as questions the customer might ask, because tapping one sends the label as
their own message.

Four situations produce no chips at all, and each is a rule rather than a taste:

    human takeover   the AI must not steer a conversation a person owns
    withdrawal       the customer said no; offering options is pestering
    restricted       a case is being opened; do not simultaneously offer
                     AI-suggested directions
    not qualified    nothing is being sold here
"""
from __future__ import annotations

from dataclasses import dataclass

from ..domain.detection import Detection
from ..domain.enums import Intent, OpportunityState, Qualification, Signal

MAX_CHIPS = 3
MAX_LABEL_CHARS = 24


@dataclass(frozen=True)
class QuickReply:
    id: str
    label: str


# Every chip in the system, defined once so the contract limits can be checked
# against the whole catalogue rather than against whatever a given turn happens to
# produce.
_ALL = {
    "qr_what_plans": QuickReply("qr_what_plans", "What plans are there?"),
    "qr_how_it_works": QuickReply("qr_how_it_works", "How does cover work?"),
    "qr_who_can_apply": QuickReply("qr_who_can_apply", "Who can apply?"),
    "qr_compare_plans": QuickReply("qr_compare_plans", "Compare the plans"),
    "qr_whats_covered": QuickReply("qr_whats_covered", "What is covered?"),
    "qr_waiting_period": QuickReply("qr_waiting_period", "Any waiting period?"),
    "qr_how_to_claim": QuickReply("qr_how_to_claim", "How do I claim?"),
    "qr_how_to_apply": QuickReply("qr_how_to_apply", "How do I apply?"),
    "qr_how_to_pay": QuickReply("qr_how_to_pay", "How can I pay?"),
    "qr_documents": QuickReply("qr_documents", "What documents?"),
    "qr_add_family": QuickReply("qr_add_family", "Add a family member"),
    "qr_for_employees": QuickReply("qr_for_employees", "Cover for employees"),
    "qr_talk_to_person": QuickReply("qr_talk_to_person", "Talk to a person"),
    "qr_more_details": QuickReply("qr_more_details", "Tell me more"),
}

# Where the conversation is decides what is worth offering next.
_BY_STATE = {
    OpportunityState.COLD_LEAD: ("qr_what_plans", "qr_how_it_works", "qr_who_can_apply"),
    OpportunityState.POTENTIAL_INTEREST: (
        "qr_compare_plans", "qr_whats_covered", "qr_who_can_apply",
    ),
    OpportunityState.EVALUATION_HESITATION: (
        "qr_whats_covered", "qr_waiting_period", "qr_how_to_apply",
    ),
    OpportunityState.HIGH_INTENT: ("qr_how_to_apply", "qr_documents", "qr_how_to_pay"),
    OpportunityState.CLOSED_ACTIVE: (
        "qr_how_to_claim", "qr_add_family", "qr_talk_to_person",
    ),
    # Nothing for Dormant/Lost: the customer has stepped away, and re-engagement is
    # a deliberate human decision rather than a chip.
    OpportunityState.DORMANT_LOST: (),
}

# A few intents shift what is most useful, without overriding the state.
_BY_INTENT = {
    Intent.CORPORATE_NEED: ("qr_for_employees",),
    Intent.FAMILY_NEED: ("qr_add_family",),
    Intent.CLAIMS: ("qr_how_to_claim",),
    Intent.PAYMENT: ("qr_how_to_pay",),
}


def catalogue() -> list[QuickReply]:
    """Every chip that can ever be offered. Exposed so the contract limits can be
    asserted across the whole set rather than sampled."""
    return list(_ALL.values())


def more_details() -> QuickReply:
    return _ALL["qr_more_details"]


def suggest(opp, det: Detection) -> list[QuickReply]:
    """Up to three chips for this turn, or an empty list.

    Pure: same conversation state, same chips in the same order, which is what makes
    the ids worth logging.
    """
    if opp.human_takeover:
        return []
    if opp.qualification is not Qualification.QUALIFIED:
        return []
    if det.restricted:
        return []
    if Signal.WITHDRAWAL in set(det.signals) | set(opp.signals):
        return []

    ordered: list[str] = []
    for key in _BY_INTENT.get(det.intent, ()):
        if key not in ordered:
            ordered.append(key)
    for key in _BY_STATE.get(opp.state, ()):
        if key not in ordered:
            ordered.append(key)

    return [_ALL[key] for key in ordered[:MAX_CHIPS]]
