# -*- coding: utf-8 -*-
"""LLM-backed customer reply generator (FR-09 with a real language model).

Safety design:
- the model is only used to phrase a reply; it receives retrieved facts and is
  instructed to use them exclusively (grounding, no invented product facts);
- escalation replies are deterministic and never generated by the model;
- any provider failure falls back to the rule-based ResponseGenerator so the
  system keeps working offline.
"""
from __future__ import annotations

from .. import config
from ..logging_utils import setup_logging
from ..models import Detection, HumanCase, NextBestAction, Opportunity, RetrievalResult
from ..providers import LLMClient, StubLLMClient
from .generator import ResponseGenerator

_SYSTEM_PROMPT = (
    "You are SalesPilot, CareSure's AI sales assistant chatting on WhatsApp. "
    "Rules: (1) Use ONLY the approved knowledge-base facts provided; never "
    "invent premiums, coverage, eligibility, claims or underwriting details. "
    "(2) Never give personalised medical, underwriting, claims or pricing "
    "decisions. (3) Be concise, warm and professional, in plain English. "
    "(4) When premium figures are shown, append this disclaimer verbatim: \""
    + config.DEMO_DISCLAIMER
    + "\""
)


class LLMResponseGenerator:
    def __init__(
        self,
        llm_client: LLMClient | None = None,
        fallback: ResponseGenerator | None = None,
        max_history: int = 4,
    ) -> None:
        self.llm = llm_client or StubLLMClient()
        self.fallback = fallback or ResponseGenerator()
        self.max_history = max_history
        self.logger = setup_logging()

    def generate(
        self,
        opp: Opportunity,
        det: Detection,
        retrieval: RetrievalResult,
        case: HumanCase | None,
        nba: NextBestAction | None = None,
    ) -> str:
        # Escalation messages stay deterministic and compliance-safe
        if case is not None:
            return self.fallback.generate(opp, det, retrieval, case, nba=nba)

        prompt = self._build_user_prompt(opp, det, retrieval)
        history = [
            {"role": "assistant" if m.role == "agent" else "user",
             "content": m.text}
            for m in opp.messages[-(self.max_history + 1):-1]
        ]
        messages = (
            [{"role": "system", "content": _SYSTEM_PROMPT}]
            + history
            + [{"role": "user", "content": prompt}]
        )
        try:
            reply = self.llm.generate(messages, temperature=0.2, max_tokens=600)
            if reply and reply.strip():
                return reply.strip()
            raise ValueError("Empty LLM reply")
        except Exception as exc:  # Provider/network/key issues -> safe fallback
            self.logger.warning("LLM generation failed, using template: %s", exc)
            return self.fallback.generate(opp, det, retrieval, case, nba=nba)

    @staticmethod
    def _build_user_prompt(
        opp: Opportunity,
        det: Detection,
        retrieval: RetrievalResult,
    ) -> str:
        facts = "\n".join(f"- {fact}" for fact in retrieval.facts)
        signals = ", ".join(s.value for s in det.signals) or "none"
        latest = opp.messages[-1].text if opp.messages else ""
        return (
            f"Approved knowledge-base facts (retrieval confidence "
            f"{retrieval.confidence:.2f}):\n{facts}\n\n"
            f"Detected intent: {det.intent.value}; product: {opp.product.value}; "
            f"sales signals: {signals}; opportunity state: {opp.state.value}.\n\n"
            f"Customer message: {latest}\n\n"
            "Write one concise WhatsApp-style reply using only the facts above."
        )
