# -*- coding: utf-8 -*-
"""A single conversation message, across three orthogonal axes.

    role        which side of the conversation   customer | business
    author      who wrote it                    ai | human | system | None
    generation  how it was produced             llm | template | human | None

Only five combinations are meaningful, and they are enumerated in
`docs/api/interface-v1.md` §5.7. This module rejects the rest at construction, so
an impossible message — a human whose words were "generated by a template", or a
business reply that will not say whether a model produced it — cannot be stored
and later rendered to somebody as if it were true.

Prefer the named constructors over the raw dataclass. They make the five valid
states convenient and the invalid ones awkward, which is the cheapest form of
correctness available here.
"""
from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, Union

from .enums import Generation, MessageAuthor, MessageRole

# The five combinations from interface-v1 §5.7, as (author, generation).
_VALID_BUSINESS_COMBINATIONS: frozenset[tuple[MessageAuthor, Generation]] = frozenset(
    {
        (MessageAuthor.AI, Generation.LLM),
        (MessageAuthor.AI, Generation.TEMPLATE),
        (MessageAuthor.HUMAN, Generation.HUMAN),
        (MessageAuthor.SYSTEM, Generation.TEMPLATE),
    }
)


def _now() -> datetime:
    return datetime.now()


def _new_id() -> str:
    return f"m-{uuid.uuid4().hex[:12]}"


@dataclass
class Message:
    role: MessageRole
    text: str
    id: str = field(default_factory=_new_id)
    ts: datetime = field(default_factory=_now)

    # Business-side only. Both None for a customer message, both set otherwise.
    author: Optional[MessageAuthor] = None
    generation: Optional[Generation] = None

    # Set only when a human representative wrote the message.
    rep_name: Optional[str] = None

    # The client's idempotency key for the request that produced this message.
    # Set on customer messages sent with one, and on a representative reply.
    client_message_id: Optional[str] = None

    def __post_init__(self) -> None:
        self._validate()

    # ---- Validation ------------------------------------------------------

    def _validate(self) -> None:
        if self.role is MessageRole.CUSTOMER:
            if self.author is not None or self.generation is not None:
                raise ValueError(
                    "A customer message carries no author and no generation: "
                    "`role` already says the customer wrote it. Got "
                    f"author={self.author!r}, generation={self.generation!r}."
                )
            if self.rep_name is not None:
                raise ValueError("rep_name is meaningless on a customer message.")
            return

        # Business side.
        if self.author is None or self.generation is None:
            raise ValueError(
                "A business-side message must state who wrote it and how it was "
                "produced, so a template reply is never mistaken for model output. "
                f"Got author={self.author!r}, generation={self.generation!r}."
            )
        if (self.author, self.generation) not in _VALID_BUSINESS_COMBINATIONS:
            raise ValueError(
                f"author={self.author.value!r} with "
                f"generation={self.generation.value!r} is not a meaningful "
                "combination. See docs/api/interface-v1.md §5.7 for the five that "
                "are."
            )
        if self.rep_name is not None and self.author is not MessageAuthor.HUMAN:
            raise ValueError(
                "rep_name identifies a human representative and may only be set "
                f"when author is 'human'; got {self.author.value!r}."
            )

    # ---- Convenience for serialisers -------------------------------------

    @property
    def author_value(self) -> Optional[str]:
        return self.author.value if self.author else None

    @property
    def generation_value(self) -> Optional[str]:
        return self.generation.value if self.generation else None

    @property
    def is_from_customer(self) -> bool:
        return self.role is MessageRole.CUSTOMER

    @property
    def is_from_model(self) -> bool:
        """True only when a model actually produced the wording."""
        return self.generation is Generation.LLM

    # ---- Named constructors ----------------------------------------------

    @classmethod
    def from_customer(
        cls,
        text: str,
        *,
        client_message_id: Optional[str] = None,
        id: Optional[str] = None,
        ts: Optional[datetime] = None,
    ) -> "Message":
        return cls(
            role=MessageRole.CUSTOMER,
            text=text,
            client_message_id=client_message_id,
            **_identity(id, ts),
        )

    @classmethod
    def from_ai(
        cls,
        text: str,
        *,
        generation: Union[Generation, str],
        rep_name: Optional[str] = None,
        id: Optional[str] = None,
        ts: Optional[datetime] = None,
    ) -> "Message":
        """An assistant reply. `generation` distinguishes a model from a template.

        `rep_name` is accepted only so the invalid case raises here rather than
        producing a message that claims a person wrote AI output.
        """
        return cls(
            role=MessageRole.BUSINESS,
            text=text,
            author=MessageAuthor.AI,
            generation=Generation(generation),
            rep_name=rep_name,
            **_identity(id, ts),
        )

    @classmethod
    def from_human(
        cls,
        text: str,
        *,
        rep_name: Optional[str] = None,
        client_message_id: Optional[str] = None,
        id: Optional[str] = None,
        ts: Optional[datetime] = None,
    ) -> "Message":
        """A human representative's reply, typed in the admin console."""
        return cls(
            role=MessageRole.BUSINESS,
            text=text,
            author=MessageAuthor.HUMAN,
            generation=Generation.HUMAN,
            rep_name=rep_name,
            client_message_id=client_message_id,
            **_identity(id, ts),
        )

    @classmethod
    def from_system(
        cls,
        text: str,
        *,
        id: Optional[str] = None,
        ts: Optional[datetime] = None,
    ) -> "Message":
        """A deterministic notice, such as a handover announcement.

        Always `template`: a system notice is fixed wording by definition.
        """
        return cls(
            role=MessageRole.BUSINESS,
            text=text,
            author=MessageAuthor.SYSTEM,
            generation=Generation.TEMPLATE,
            **_identity(id, ts),
        )


def _identity(id: Optional[str], ts: Optional[datetime]) -> dict:
    """Pass through an explicit id/timestamp, or let the defaults apply.

    Used when reloading from storage, where both must be preserved exactly.
    """
    supplied = {}
    if id is not None:
        supplied["id"] = id
    if ts is not None:
        supplied["ts"] = ts
    return supplied
